language: php

sudo: false

php:
  - 5.4
  - 5.6
  - 7.1
  - hhvm

install:
  - composer update

script:
  - phpunit --coverage-text
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
  - phpunit --group unicode

branches:
  only:
    - master
